services:

  backend:
    build: .
    container_name: python-api
    ports:
      - "5000:5000"

    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: 1234

    depends_on:
      - redis

    networks:
      - app-network


  redis:
    image: redis:latest
    container_name: redis-server

    command: redis-server --requirepass 1234

    networks:
      - app-network


networks:
  app-network:
    driver: bridge